name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Maven
      run: mvn -B package --file pom.xml 
  coverage:

    runs-on: [ubuntu-latest]
    name: test

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Coverage with JaCoCo
        run: mvn -V clean verify jacoco:prepare-agent test integration-test jacoco:report --file pom.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.0.3
        with:
          token: face55b1-42ed-4cb5-9b63-facf0a027280

      # - name: Report coverage
      #   shell: bash
      #   env:
      #     CODACY_PROJECT_TOKEN: face55b1-42ed-4cb5-9b63-facf0a027280
      #   run: |
      #     if [ "$CODACY_PROJECT_TOKEN" != "" ]; then
      #       bash <(curl -s https://codecov.io/bash) -f "*jacoco.xml"
      #       bash <(curl -Ls https://coverage.codacy.com/get.sh) report -l Java -r integrations/target/site/jacoco-aggregate/jacoco.xml
      #     else
      #       echo "No secrets provided for coverage report"
      #     fi